### ISSUE TITLE
CLHash implementation

### ISSUE THREAD

**Issue by sigrlami** [vincenthz/hs-memory#14]
Will be implementation of CLHash
http://lemire.me/blog/2015/10/26/crazily-fast-hashing-with-carry-less-multiplications/
useful for this package? 

CLHash provides 10x preformance in contrast with SipHash.

**Comment by vincenthz** [comment]
yes, it would be cool to have for sure.

**Comment by sigrlami** [comment]
@vincenthz nice! I'll send PR in a couple of weeks.

**Comment by vincenthz** [comment]
closing this as this issue is dead
