### ISSUE TITLE
`memory` fails to build on GHC 8.0

### ISSUE THREAD

**Issue by hvr** [vincenthz/hs-memory#15]
The following snippet from `Data/Memory/Internal/CompatPrim.hs` has a clearly incorrent `>= 740` condition, so that code was effectively dead code (which doesn't compile anyway) until now.

``` hs
#if __GLASGOW_HASKELL__ >= 740
eitherDivideBy8# v f8 f1 =
    let !(# q, r #) = quotRemInt v 8#
     in if booleanPrim (r ==# 0)
            then f8 q
            else f1 v
#else
```

I've added `base < 4.9` constraints to affected `memory` releases;

This is not the only incompatibility with GHC 8.0 though; For instance, the `mkWeak#` primitive's type-signature changed.

**Comment by vincenthz** [comment]
fixed in 0.11. thanks for reporting, although please point-to / attach the error logs in the future
