### ISSUE TITLE
No documentation on Hackage for 0.12

### ISSUE THREAD

**Issue by slaymaker1907** [vincenthz/hs-memory#22]
It appears that something went horribly wrong with whatever generates the documentation. If you go to https://hackage.haskell.org/package/memory-0.12/docs/Data-ByteArray.html, it can't find any of the documentation (it has a link that is supposed to go the most recent docs, but that just leads to the same page).

However, Google apparently cached the page on March 13, 2016 so it seems to have been working at that time. Additionally, the main doc contents on Hackage work, yet there are no links to any module documentation (https://hackage.haskell.org/package/memory-0.12) but all of the modules don't have links. It appears that the docs for v0.11 are there, but there are no docs for v0.12.

**Comment by vincenthz** [comment]
oh that's unfortunate, although It does looks like a case of hackage being so crummy.

The equivalent stackage doc is correctly generated there: http://haddock.stackage.org/nightly-2016-04-20/memory-0.12/Data-ByteArray.html if that helps.

I will try to look to manually upload the doc if possible
