### ISSUE TITLE
Give `append` more general type

### ISSUE THREAD

**Issue by dylex** [vincenthz/hs-memory#25]
Most of the other functions taking multiple arrays have quite general types, but currently `append` is just an alias for `mappend`, which doesn't add much value.  Would it make sense for it to have one of the following types instead:

```
append :: (ByteArray bs, ByteArrayAccess ba) => bs -> ba -> bs
append :: (ByteArray bs, ByteArrayAccess ba1, ByteArrayAccess ba2) => ba1 -> ba2 -> bs
```

I'd suggest the first is probably reasonable. Happy to provide a PR if this seems desirable.

**Comment by vincenthz** [comment]
it can make sense on its own binding. I think the ship has sailed to change `append` now, but we could have a `append_polymorphic` (proper naming to be found). otherwise closing now
