### ISSUE TITLE
UArray IntN (N > 8) allocRet has weird length argument.

### ISSUE THREAD

**Issue by lodvaer** [vincenthz/hs-memory#32]
λ> let x = (BA.length :: UArray Int8 -> Int) . snd <$> BA.allocRet 4 (const $ return ()) in x
    4
    λ> let x = (BA.length :: UArray Int16 -> Int) . snd <$> BA.allocRet 4 (const $ return ()) in x
    8
    λ> let x = (BA.length :: UArray Int64 -> Int) . snd <$> BA.allocRet 4 (const $ return ()) in x
    32

This leads to cryptonite's block cipher encryption of a UArray Int64 to return output eight times the size of the input.

**Comment by vincenthz** [comment]
ah yes indeed, it's on my list of fix already, sorry about that ! I'll sort this mismatch really soon

**Comment by NicolasDP** [comment]
I believe I addressed this issue too in my PR #34
