### ISSUE TITLE
Deprecate `memory-0.14.12` on Hackage

### ISSUE THREAD

**Issue by Gabriella439** [vincenthz/hs-memory#46]
I ran into the following issue in one of my Travis CI builds when building `memory-0.14.12`:

```
Data/ByteArray/Methods.hs:303:1:
    No instance for (ByteArray (SPE.Block Word8))
      arising from a specialisation pragma for ‘convert’
    In the SPECIALISE pragma
      {-# SPECIALIZE convert :: SPE.ByteString -> SPE.Block Word8 #-}
Data/ByteArray/Methods.hs:305:1:
    No instance for (ByteArrayAccess (SPE.Block Word8))
      arising from a specialisation pragma for ‘convert’
    In the SPECIALISE pragma
      {-# SPECIALIZE convert :: SPE.Block Word8 -> SPE.ByteString #-}
```

I saw that this is fixed in `memory-0.14.13` so this is just a request to deprecate version `0.14.12` on Hackage so that `cabal` avoids selecting it

**Comment by vincenthz** [comment]
I'm not going to start marking this on hackage one way or another. I don't see the usefulness, either the latest should be used, or users has selected something older for whatever reason and that's their prerogatives.
