### ISSUE TITLE
Unable to build without `foundation` support

### ISSUE THREAD

**Issue by aisamanra** [vincenthz/hs-memory#56]
When you try to build `memory` with `support_foundation` disabled, you get the following error:

```
Building library for memory-0.14.14..
[ 1 of 28] Compiling Data.ByteArray.Types ( Data/ByteArray/Types.hs, dist/build/Data/ByteArray/Types.o )

Data/ByteArray/Types.hs:70:58: error:
    • Variable not in scope:
        memCopy :: Ptr b0 -> Ptr p0 -> Int -> IO ()
    • Perhaps you meant ‘Bytestring.memcpy’ (imported from Data.ByteString.Internal)
   |
70 |     copyByteArrayToPtr a dst = withByteArray a $ \src -> memCopy (castPtr dst) src (length a)
   |    
```

I'm not sure how old this problem is, but it's at least present in `0.14.14` as well as the current git HEAD. It looks like it might be because of misplaced CPP guards for `WITH_FOUNDATION_SUPPORT`. I haven't yet put together a fixed version, but I'd be happy to do so and put in a PR.

**Comment by ocheron** [comment]
Indeed import of `memCopy` should not be in the middle of the block `#ifdef WITH_FOUNDATION_SUPPORT` but outside.
