### ISSUE TITLE
Fails to build on GHC 7.10

### ISSUE THREAD

**Issue by ndmitchell** [vincenthz/hs-memory#62]
I get:

```
Building memory-0.14.15...
Failed to install memory-0.14.15
Build log ( /home/travis/.cabal/logs/ghc-7.10.3/memory-0.14.15-335len5dmIaJFsiMzbNDU3.log ):
cabal: Entering directory '/tmp/cabal-tmp-4968/memory-0.14.15'
Configuring memory-0.14.15...
Preprocessing library for memory-0.14.15..
Building library for memory-0.14.15..
Data/ByteArray/Types.hs:54:18:
    Could not find module ‘Basement.BlockN’
    Perhaps you meant
      Basement.Block (from basement-0.0.7@10XMWntHKC49TRIYbXTRxt)
    Use -v to see a list of the files searched for.
cabal: Leaving directory '/tmp/cabal-tmp-4968/memory-0.14.15'
```

Would be nice if it either failed to build, or had enough bounds that it didn't try (then new versions don't have to support GHC 7.10). You can see the failure most clearly on the CI Matrix: https://matrix.hackage.haskell.org/package/memory

**Comment by vincenthz** [comment]
currently being fixed https://travis-ci.org/vincenthz/hs-memory/jobs/346639738

**Comment by ndmitchell** [comment]
Thanks! A beer awaits you on successful completion 🍺

**Comment by vincenthz** [comment]
should be fixed in 0.14.16, and more generally after the 8.4 release, I'm going to lower bound ghc to 8.0 on everything (and then cleanup compat layers)

**Comment by vincenthz** [comment]
bit early for :beer: but I'll take it !

**Comment by ndmitchell** [comment]
As long as you clamp to 8.0 via a base constraint, older versions should use older pieces, and that will be fine. One thing to note is that may require going back to slightly older versions (the last one to support GHC 7.x) and doing Hackage revisions to keep their bounds working...

**Comment by vincenthz** [comment]
I'll use the `impl(ghc)` constraint which I find much more appropriate than using base version as a proxy.
I don't see why it should need revisions in this case, surely the solver should prevent newer version to be used if this is not buildable for 7.8/7.10 and should automatically backtrack to older version ?

**Comment by ndmitchell** [comment]
I forget about `impl(ghc)` - that does seem much better. All working now - thanks.
