### ISSUE TITLE
Allow custom index

### ISSUE THREAD

**Issue by domenkozar** [vincenthz/hs-memory#67]
hey @vincenthz,

[Nix uses custom base32 index for legacy reasons](https://github.com/NixOS/nix/blob/master/src/libutil/hash.cc#L73), would you be opposed making [index as an input](https://github.com/vincenthz/hs-memory/blob/master/Data/Memory/Encoding/Base32.hs#L107) in memory?

**Comment by vincenthz** [comment]
I was convinced I already answered, weirdly, but looks like not.
I don't have a problem making a base32 with customizable dictionary, although this might react funny with the lowlevelness of the module (some of it is unwarranted though)

**Comment by domenkozar** [comment]
Thanks - I'll look into it.

**Comment by domenkozar** [comment]
Best to just translate back and forth between indexes - for now.
