### ISSUE TITLE
fails to build on arm

### ISSUE THREAD

**Issue by joeyh** [vincenthz/hs-memory#7]
[13 of 28] Compiling Data.Memory.Endian ( Data/Memory/Endian.hs, dist/build/Data/Memory/Endian.o )

Data/Memory/Endian.hs:51:39: Not in scope: `alloca'

Data/Memory/Endian.hs:53:35: Not in scope: `castPtr'

Data/Memory/Endian.hs:53:48:
    Not in scope: type constructor or class `Ptr'

Data/Memory/Endian.hs:53:52:
    Not in scope: type constructor or class `Word8'

This is on a little-endian arm machine, Debian armel architecture.  I see in the cabal file there's a comment about runtime detection being needed. Hacking the cabal file got it to build.

**Comment by vincenthz** [comment]
I've fixed the runtime detection to compile; there's sadly no way to distinguish armel vs arm through the cabal arch call.
