### ISSUE TITLE
ScrubbedBytes should offer prompt scrubbing

### ISSUE THREAD

**Issue by treeowl** [vincenthz/hs-memory#83]
There's no way to ensure that a `ScrubbedBytes` gets scrubbed promptly once operations on it complete. See [this StackOverflow answer](https://stackoverflow.com/a/62156413/1477667). There ~~are two~~ is one obvious way to fix this:

1. ~~Include the weak pointer in the `ScrubbedBytes` type, so it can be finalized with a `scrub :: ScrubbedBytes -> IO ()` function. I suspect this is the best approach.~~

2. Offer a `ScrubbedBytes` creation function that also produces the weak pointer. ~~This seems awkward, and the potential performance improvement when the user doesn't finalize manually strikes me as pretty insignificant.~~

**Comment by ocheron** [comment]
Can't the `scrub` function be implemented for all existing instances of `ByteArrayAccess`?

**Comment by treeowl** [comment]
Wait a second.... What was I thinking? We really do need the weak pointer to be returned separately; otherwise we won't be able to release the memory through garbage collection! Option 1 is garbage. Oops. So no, we can't do this for all instances, and only Option 2 is sensible.

**Comment by treeowl** [comment]
The way to do it is to return the `ScrubbedBytes` and an `IO` action to finalize/scrub.

**Comment by ocheron** [comment]
I'm not opposed to more stuff if that's useful but just reacting to "there is no way to scrub promptly". If you want to zero out the bytearray yourself, you can do it at any time with `withByteArray` and don't need `ScrubbedBytes`.

**Comment by treeowl** [comment]
Ah, I see. Maybe we don't need this then! Wasn't thinking too carefully, was I?

**Comment by ocheron** [comment]
Many functions in the API give illusion that the buffers are immutable but they're not.

Capturing the pattern in a `withTemporary` function could be useful though.

**Comment by treeowl** [comment]
Sorry for closing/reopening, but I still think there's something to be done here. The pattern I'm hoping to support looks like

1. Get some bytes.
2. Use the bytes in a computation that may or may not drop them to the GC before completion. If they're dropped, scrub them.
3. Make sure the bytes have been scrubbed by now.

`ScrubbedBytes` can currently do 2 but not 3. The other approach can do 3 but not 2. To get both at once, we need access to `finalize` the `Weak`, most ergonomically represented as `IO ()`.

**Comment by ocheron** [comment]
Let's not forget the type is mutable. After an explicit scrub, it's still possible to write secret data again. So you have scenarios where a (new?) Weak will be useful later too.

**Comment by treeowl** [comment]
Sure, I suppose you could make all the weak pointers you want to one `ScrubbedBytes`. We could have `mkScrubber :: ScrubbedBytes -> IO (IO ())` to do that. But week pointers aren't at all free, so it seems a shame not to let the user get at that initial one.
